/*
 * Inlines src/ and vendor/ into the single self-contained pdf-filler.html.
 *
 *   node build.mjs
 *
 * The output has no external references at all, so it works offline and
 * straight off the filesystem. pdf.js's worker is inlined alongside the
 * library: with no separate URL to start a worker from, pdf.js picks the
 * script up as globalThis.pdfjsWorker and parses on the main thread.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const read = (...p) => readFileSync(join(here, ...p), 'utf8');

const CREDITS = `<!--
  PDF Filler — a single-file AcroForm filler. Generated by build.mjs;
  edit src/ and rebuild rather than editing this file.

  Bundled: pdf.js 3.11.174 (Apache-2.0, Mozilla Foundation) and
  pdf-lib 1.17.1 (MIT, Andrew Dillon). Full licence texts live in
  vendor/LICENSE.pdfjs and vendor/LICENSE.pdf-lib.
-->`;

const script = (source) => `<script>\n${source}\n</script>`;

// Guard the one thing that would corrupt a bundle: a minified library
// containing </script would close the tag early.
for (const name of ['pdf.min.js', 'pdf.worker.min.js', 'pdf-lib.min.js']) {
  if (/<\/script/i.test(read('vendor', name))) {
    throw new Error(`vendor/${name} contains </script and cannot be inlined verbatim`);
  }
}

const libs = [
  script(read('vendor', 'pdf.min.js')),
  script(read('vendor', 'pdf.worker.min.js')),
  script(read('vendor', 'pdf-lib.min.js')),
].join('\n');

// Replacements are functions so that $&, $' and friends in the minified
// sources are not treated as replacement patterns.
const html = read('src', 'page.html')
  .replace('<!--STYLES-->', () => `<style>\n${read('src', 'styles.css')}\n</style>`)
  .replace('<!--LIBS-->', () => libs)
  .replace('<!--APP-->', () => script(read('src', 'app.js')));

const out = join(here, 'pdf-filler.html');
writeFileSync(out, `${CREDITS}\n${html}`);
console.log(`wrote ${out} (${(Buffer.byteLength(html) / 1e6).toFixed(2)} MB)`);
